
[package]
name = "solders-rpc-program-accounts-config"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }
description = "Solders RPC program accounts config crate."

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
serde = { workspace = true }
solana-rpc-client-types = { workspace = true }
solders-macros = { workspace = true }
solders-rpc-account-info-config = { workspace = true }
solders-rpc-config-macros = { workspace = true }
solders-rpc-filter = { workspace = true }
solders-traits-core = { workspace = true }
