class CommitmentLevel:
    Processed: CommitmentLevel
    Confirmed: CommitmentLevel
    Finalized: CommitmentLevel
    def __int__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, o: object) -> bool: ...
    @staticmethod
    def from_string(s: str) -> CommitmentLevel: ...
