from typing import Union
from .solders import (
    UiTransactionEncoding,
    TransactionDetails,
    TransactionBinaryEncoding,
    ParsedInstruction,
    UiPartiallyDecodedInstruction,
    UiCompiledInstruction,
    UiAddressTableLookup,
    UiParsedMessage,
    UiRawMessage,
    ParsedAccountSource,
    ParsedAccount,
    VersionedTransaction, 
    UiTransaction,
    UiAccountsList,
    UiInnerInstructions,
    UiLoadedAddresses,
    UiTransactionTokenBalance,
    Reward,
    RewardType,
    TransactionReturnData,
    UiTransactionStatusMeta,
    EncodedTransactionWithStatusMeta,
    TransactionConfirmationStatus,
    TransactionStatus,
    EncodedConfirmedTransactionWithStatusMeta,
    UiConfirmedBlock,
    InstructionErrorFieldless,
    InstructionErrorCustom,
    InstructionErrorBorshIO,
    TransactionErrorFieldless,
    TransactionErrorInstructionError,
    TransactionErrorDuplicateInstruction,
    TransactionErrorInsufficientFundsForRent,
    TransactionErrorProgramExecutionTemporarilyRestricted,
)

UiParsedInstruction = Union[ParsedInstruction, UiPartiallyDecodedInstruction]
UiInstruction = Union[UiParsedInstruction, UiCompiledInstruction]
UiMessage = Union[UiParsedMessage, UiRawMessage]
EncodedVersionedTransaction = Union[VersionedTransaction, UiTransaction, UiAccountsList]
InstructionErrorType = Union[
    InstructionErrorFieldless,
    InstructionErrorCustom,
    InstructionErrorBorshIO,
]
TransactionErrorType = Union[
    TransactionErrorFieldless,
    TransactionErrorInstructionError,
    TransactionErrorDuplicateInstruction,
    TransactionErrorInsufficientFundsForRent,
    TransactionErrorProgramExecutionTemporarilyRestricted,
]

__all__ = [
"UiTransactionEncoding",
"TransactionDetails",
"TransactionBinaryEncoding",
"ParsedInstruction",
"UiPartiallyDecodedInstruction",
"UiCompiledInstruction",
"UiAddressTableLookup",
"UiParsedMessage",
"UiRawMessage",
"ParsedAccountSource",
"ParsedAccount",
"VersionedTransaction," 
"UiTransaction",
"UiAccountsList",
"UiInnerInstructions",
"UiLoadedAddresses",
"UiTransactionTokenBalance",
"Reward",
"RewardType",
"TransactionReturnData",
"UiTransactionStatusMeta",
"EncodedTransactionWithStatusMeta",
"TransactionConfirmationStatus",
"TransactionStatus",
"EncodedConfirmedTransactionWithStatusMeta",
"UiConfirmedBlock",
"InstructionErrorFieldless",
"InstructionErrorCustom",
"InstructionErrorBorshIO",
"TransactionErrorFieldless",
"TransactionErrorInstructionError",
"TransactionErrorDuplicateInstruction",
"TransactionErrorInsufficientFundsForRent",
"TransactionErrorProgramExecutionTemporarilyRestricted",
"UiParsedInstruction",
"UiInstruction",
"UiMessage",
"EncodedVersionedTransaction",
"InstructionErrorType",
"TransactionErrorType"
]