
[package]
name = "solders-rpc-sim-transaction-config"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }
description = "Solders RPC simulate transaction config crate."

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
serde = { workspace = true }
solana-rpc-client-types = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
solders-commitment-config = { workspace = true }
solders-macros = { workspace = true }
solders-rpc-config-macros = { workspace = true }
solders-rpc-simulate-tx-accounts-config = { workspace = true }
solders-traits-core = { workspace = true }
solders-transaction-status-enums = { workspace = true }
