
[package]
name = "solders-rpc-simulate-tx-accounts-config"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }
description = "Solders RPC simulate transaction accounts crate."

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
serde = { workspace = true }
solana-rpc-client-types = { workspace = true }
solders-account-decoder = { workspace = true }
solders-macros = { workspace = true }
solders-pubkey = { workspace = true }
solders-rpc-config-macros = { workspace = true }
solders-traits-core = { workspace = true }
